version: '3.8'
services:
  # Thay mysqldb bằng postgresdb
  postgresdb:
    image: postgres:15-alpine # Bản nhẹ và ổn định
    container_name: wims-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres # Mặc định là postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wims_db
    ports:
      - "5432:5432" # Port mặc định của Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis giữ nguyên
  redis:
    image: redis:alpine
    container_name: wims-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: # Đổi tên volume cho đúng chuẩn