server:
  port: 8080

spring:
  application:
    name: wims-backend

  # Cấu hình Database cho PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/wims_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: false

  # Cấu hình JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB      # Giới hạn cho từng file riêng lẻ
      max-request-size: 50MB   # Giới hạn cho tổng cả request (gồm file + data)

  mail:
    host: smtp.gmail.com
    port: 587
    username: lyxuantin113@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

frontend:
  baseurl: ${FE_URL:http://localhost:5173}

cloudinary:
  cloudname: ${CLOUDINARY_NAME}
  key: ${CLOUDINARY_KEY}
  secret: ${CLOUDINARY_SECRET}
  secure: true

vnpay:
  payurl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnurl: ${FE_URL}/payment-result
  tmncode: ${VNP_TMN_CODE}
  hashsecret: ${VNP_HASH_SECRET}
  apiurl: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

jwt:
  secretkey: ${JWT_SECRET_KEY:ChuoiBiMatNgaoNhienSieuDai123456}
  expiration: "60000"
