spring:
  config:
    activate:
      on-profile: prod


  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      ssl:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

jwt:
  expiration: "300000"
  refresh-expiration: "1800000"