server:
  port: 8080

spring:
  application:
    name: wims-backend

  # Cấu hình Database cho PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/wims_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: http://localhost:5173
      port: 6379
      repositories:
        enabled: false
      ssl:
        enabled: false

  # Cấu hình JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB      # Giới hạn cho từng file riêng lẻ
      max-request-size: 50MB   # Giới hạn cho tổng cả request (gồm file + data)

  mail:
    host: smtp.gmail.com
    port: 587
    username: lyxuantin113@gmail.com
    password: kzhozerfsagcpyon
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

frontend:
  baseurl: http://localhost:5173

cloudinary:
  cloudname: dfdyfg6bd
  key: 374153475555556
  secret: SUfU3BPGWnPM-B6AT_6aNWZvcUU
  secure: true

vnpay:
  payurl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnurl: http://localhost:5173/payment-result
  tmncode: EP00AIH4
  hashsecret: TIKM7PQZ7600Y1LRDG383QB13SVX13M8
  apiurl: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

jwt:
  secretkey: LyXuanTinIndustrialUniversityOfHoChiMinhCity_1234567890_SafeKey_Security
  expiration: "60000"
  refresh-expiration: "1800000"
